In [1]:
import sys
import numpy as np
import time


In [2]:
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
  print("Hello, World!")
  print(f"Python version: {sys.version}")
else:
  print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [3]:
#Mutable Data Type Example(List)
my_list = [1, 2, 3]
print("Original List:", my_list)

#Modifying the list (Changing contents)
my_list . append(4)
print("Modified List:", my_list)

#Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
#my_tuple. append(4)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [4]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi ))
print("data type of variable temperature = ", type(temperature))


data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [5]:
# declaring string variables
name = "Alice"
message = "Hello"
location = "123 Main St"

# checking the data type of each variable
print("Data type of name:", type(name))
print("Data type of message:", type(message))
print("Data type of location:", type(location))

# accessing single characters using indexing
print("First character of the name:", name[0])
print("Last character of the name:", name[-1])

# slicing a part of the string
print("Characters from position 2 to 4:", name[1:4])
print("First two characters of the name:", name[:2])
print("Characters starting from the third position:", name[2:])

Data type of name: <class 'str'>
Data type of message: <class 'str'>
Data type of location: <class 'str'>
First character of the name: A
Last character of the name: e
Characters from position 2 to 4: lic
First two characters of the name: Al
Characters starting from the third position: ice


In [6]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [7]:
# creating a tuple of colors
color_list = ('red', 'green', 'yellow', 'blue')

# accessing elements from the tuple
print("First color:", color_list[0])
print("Last two colors:", color_list[2:])
print("Middle colors:", color_list[1:3])

# trying to change a tuple element (this will cause an error)
# color_list[0] = 'purple'

print(color_list)   # tuples cannot be changed because they are immutable

First color: red
Last two colors: ('yellow', 'blue')
Middle colors: ('green', 'yellow')
('red', 'green', 'yellow', 'blue')


In [8]:
# creating a dictionary for a person's information
person_info = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}

# printing the information using formatted string
print(f"My name is {person_info['name']}. I am {person_info['age']} years old and I live in {person_info['city']}.")

# displaying dictionary keys and values
print("Dictionary keys:", list(person_info.keys()))
print("Dictionary values:", list(person_info.values()))

My name is John. I am 30 years old and I live in Pittsburgh.
Dictionary keys: ['name', 'age', 'city']
Dictionary values: ['John', 30, 'Pittsburgh']


In [9]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [10]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [11]:
num = 10
if num > 0:
  print("Positive")
elif num == 0:
  print("Zero")
else:
  print("Non-positive")

Positive


In [12]:
x = 5
y = 10
if x > 0 and y < 20:
  print("Both conditions are true")
if x > 0 or y > 20:
  print("At least one condition is true")
if not x == 0:
  print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [13]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
  print("Both a and b are True")
else:
  print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
  print("At least one of a or b is True") # This will be printed
else:
  print("Both a and b are False")
# Using the ’not’ operator
if not a:
  print("a is False") # This will not be printed
else:
  print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


In [15]:
# For loop example
fruit_list = ["apple", "banana", "cherry"]

print("Printing fruits using a for loop:")
for item in fruit_list:
    print(item)


# While loop example
number = 0
print("\nPrinting numbers using a while loop:")
while number < 5:
    print("Current number:", number)
    number += 1


# Break example
more_fruits = ["apple", "banana", "orange"]

print("\nLoop with break statement:")
for item in more_fruits:
    print(item)
    if item == "apple":
        break   # stops the loop when apple is found


# Continue example
print("\nLoop with continue statement:")
for item in more_fruits:
    if item == "apple":
        continue   # skips apple
    print(item)

Printing fruits using a for loop:
apple
banana
cherry

Printing numbers using a while loop:
Current number: 0
Current number: 1
Current number: 2
Current number: 3
Current number: 4

Loop with break statement:
apple

Loop with continue statement:
banana
orange


In [16]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.

    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer

    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a + b)[2:]
    return binary_sum

# Call the function and print the result
print(add_binary(1, 2))

11


In [17]:
# Print Hello, World!
print("Hello, World!")  # Output: Hello, World!

# Length of a string
length = len("Hello")
print("Length of 'Hello':", length)  # Output: 5

# Data type of a value
data_type = type(42)
print("Data type of 42:", data_type)  # Output: <class 'int'>

# Sum of a list
total = sum([1, 2, 3])
print("Sum of [1, 2, 3]:", total)  # Output: 6

Hello, World!
Length of 'Hello': 5
Data type of 42: <class 'int'>
Sum of [1, 2, 3]: 6


In [18]:
# str.upper() : converts all letters in a string to uppercase
text = "hello".upper()
print("Text in uppercase:", text)   # Output: HELLO


# list.append() : adds a new element at the end of a list
fruit_list = ["apple", "banana"]
fruit_list.append("cherry")
print("Fruits after adding new item:", fruit_list)   # Output: ['apple', 'banana', 'cherry']


# dict.get() : retrieves the value of a given key from a dictionary
person_info = {"name": "Alice", "age": 25}
person_age = person_info.get("age")
print("Age obtained from dictionary:", person_age)   # Output: 25

Text in uppercase: HELLO
Fruits after adding new item: ['apple', 'banana', 'cherry']
Age obtained from dictionary: 25


In [19]:
def temperature_converter():
  '''
  Converts temperature between Celsius and Fahrenheit.
  This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
  Fahrenheit to Celsius)
  and then asks for the temperature value. It calculates and returns the converted temperature.
  Returns:
  float: The converted temperature value.
  '''
  print("Choose conversion type:")
  print("1. Celsius to Fahrenheit")
  print("2. Fahrenheit to Celsius")
  # Get conversion choice from user
  choice = input("Enter 1 or 2: ")
  if choice == "1":
    celsius = float(input("Enter temperature in Celsius: "))
    fahrenheit = (celsius * 9/5) + 32
    print(f"{celsius}C is equal to {fahrenheit}F")
    return fahrenheit
  elif choice == "2":
    fahrenheit = float(input("Enter temperature in Fahrenheit: "))
    celsius = (fahrenheit - 32) * 5/9
    print(f"{fahrenheit}F is equal to {celsius}C")
    return celsius
  else:
    print("Invalid choice. Please enter 1 or 2.")
    return None

# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 2
Enter temperature in Fahrenheit: 34
34.0F is equal to 1.1111111111111112C


1.1111111111111112

In [20]:
x = 10 # Global Variable.
def print_global():
  print(x) # Accessing global variable
print_global() # Output: 10

10


In [21]:
def print_local():
    y = 5  # Local variable
    print("Inside function:", y)

print_local()  # Output: 5



Inside function: 5


In [22]:
x = 10 # Global variable
def modify_global():
  global x # Declaring x as global
x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


TO-DO-TASK EXERCISE ON FUNCTION TASK-1

In [23]:
def convert_units(value, conversion_type):
    """
    Performs conversion between different units.

    Parameters:
    value (float): The numeric value to convert.
    conversion_type (int): The choice representing the specific conversion type.

    Returns:
    float: The converted value.

    Raises:
    ValueError: If conversion_type is invalid.
    """
    # Conversion factors
    METERS_TO_FEET = 3.28084
    KG_TO_LBS = 2.20462
    LITERS_TO_GALLONS = 0.264172

    if conversion_type == 1:
        return value * METERS_TO_FEET
    elif conversion_type == 2:
        return value / METERS_TO_FEET
    elif conversion_type == 3:
        return value * KG_TO_LBS
    elif conversion_type == 4:
        return value / KG_TO_LBS
    elif conversion_type == 5:
        return value * LITERS_TO_GALLONS
    elif conversion_type == 6:
        return value / LITERS_TO_GALLONS
    else:
        raise ValueError("Invalid conversion choice.")


def main_converter():
    while True:
        print("\nUnit Conversion Program")
        print("1. Meters to Feet")
        print("2. Feet to Meters")
        print("3. Kilograms to Pounds")
        print("4. Pounds to Kilograms")
        print("5. Liters to Gallons")
        print("6. Gallons to Liters")
        print("0. Exit")

        try:
            choice = int(input("Select conversion (0-6): "))
            if choice == 0:
                print("Exiting program.")
                break
            value = float(input("Enter the value to convert: "))
            converted_value = convert_units(value, choice)
            print(f"Converted value: {converted_value:.2f}")
        except ValueError as e:
            print(f"Error: {e}. Please enter numeric values and valid choices only.")


if __name__ == "__main__":
    main_converter()


Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 5
Enter the value to convert: 55
Converted value: 14.53

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 3
Enter the value to convert: 22
Converted value: 48.50

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 6
Enter the value to convert: 33
Converted value: 124.92

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
0. Exit
Select conversion (0-6): 0
Exiting program.


Task 2

In [24]:
def get_sum(numbers):
    """Calculates the sum of all numbers in a list."""
    return sum(numbers)

def get_average(numbers):
    """Calculates the arithmetic mean of a list of numbers."""
    return sum(numbers) / len(numbers) if numbers else 0

def get_max(numbers):
    """Finds the maximum value in a list of numbers."""
    return max(numbers)

def get_min(numbers):
    """Finds the minimum value in a list of numbers."""
    return min(numbers)

def main():
    print("Math operations on Lists")
    print("Available operations: sum, average, max, min")
    print("Type 'exit' to quit the program.")

    while True:
        operation = input("\nEnter the operation (sum, average, max, min) or 'exit': ").strip().lower()
        if operation == "exit":
            print("Exiting program.")
            break

        numbers_str = input("Enter a list of numbers separated by spaces: ").strip()
        try:
            numbers = [float(num) for num in numbers_str.split()]
            if not numbers:
                print("The list is empty. Please enter at least one number.")
                continue

            if operation == "sum":
                result = get_sum(numbers)
            elif operation == "average":
                result = get_average(numbers)
            elif operation == "max":
                result = get_max(numbers)
            elif operation == "min":
                result = get_min(numbers)
            else:
                print("Invalid operation. Please choose from sum, average, max, or min.")
                continue

            print(f"Result: {result}")

        except ValueError:
            print("Error: Please enter numeric values only.")

if __name__ == "__main__":
    main()

Math operations on Lists
Available operations: sum, average, max, min
Type 'exit' to quit the program.

Enter the operation (sum, average, max, min) or 'exit': sum
Enter a list of numbers separated by spaces: 2
Result: 2.0

Enter the operation (sum, average, max, min) or 'exit': exit
Exiting program.


In [25]:
# List Manipulation Functions

# Function to return every alternate element
def get_alternate_elements(lst):
    """Return every other element starting from the first position."""
    return lst[::2]

# Function to get a portion of the list
def slice_sublist(lst, start, end):
    """Return elements from start index to end index."""
    return lst[start:end+1]

# Function to reverse a list
def list_reverse(lst):
    """Return the list in reversed order."""
    return lst[::-1]

# Function to remove first and last items
def trim_list(lst):
    """Return the list without the first and last elements."""
    return lst[1:-1]

# Function to get first n elements
def first_n_elements(lst, n):
    """Return the first n items from the list."""
    return lst[:n]

# Function to get last n elements
def last_n_elements(lst, n):
    """Return the last n items from the list."""
    return lst[-n:]

# Function to get elements in reverse order skipping one
def reverse_skip_elements(lst):
    """Return every second element starting from the second last going backward."""
    return lst[-2::-2]


# Testing the functions
sample_list = [1,2,3,4,5,6,7,8,9,10]

print("Original list:", sample_list)
print("Alternate elements:", get_alternate_elements(sample_list))
print("Sublist (2-4):", slice_sublist(sample_list, 2, 4))
print("Reversed list:", list_reverse(sample_list))
print("Without first and last:", trim_list(sample_list))
print("First 3 elements:", first_n_elements(sample_list, 3))
print("Last 2 elements:", last_n_elements(sample_list, 2))
print("Reverse skip:", reverse_skip_elements(sample_list))

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Alternate elements: [1, 3, 5, 7, 9]
Sublist (2-4): [3, 4, 5]
Reversed list: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Without first and last: [2, 3, 4, 5, 6, 7, 8, 9]
First 3 elements: [1, 2, 3]
Last 2 elements: [9, 10]
Reverse skip: [9, 7, 5, 3, 1]


In [26]:
# Basic Flatten
def flatten(data):
    result = []
    for group in data:
        for value in group:
            result.append(value)
    return result


# Accessing Elements
def access_nested_element(data, index_list):
    value = data
    for i in index_list:
        value = value[i]
    return value


# Deep Flatten
def deep_flatten(data):
    output = []
    for element in data:
        if type(element) == list:
            output += deep_flatten(element)
        else:
            output.append(element)
    return output


# Sum (works for any depth)
def sum_nested(data):
    numbers = deep_flatten(data)
    total = 0
    for n in numbers:
        total += n
    return total


# Remove Element
def remove_element(data, target):
    new_list = []
    for element in data:
        if isinstance(element, list):
            new_list.append(remove_element(element, target))
        else:
            if element != target:
                new_list.append(element)
    return new_list


# Max value
def find_max(data):
    values = deep_flatten(data)
    return max(values)


# Count occurrences
def count_occurrences(data, target):
    values = deep_flatten(data)
    count = 0
    for v in values:
        if v == target:
            count += 1
    return count


# Average
def average_nested(data):
    numbers = deep_flatten(data)
    if len(numbers) == 0:
        return 0
    return sum(numbers) / len(numbers)


print("1. Flatten:", flatten([[1, 2], [3, 4], [5]]))
print("2. Access:", access_nested_element([[1, 2, 3], [4, 5, 6]], [1, 2]))
print("3. Sum:", sum_nested([[1, 2], [3, [4, 5]], 6]))
print("4. Remove:", remove_element([[1, 2], [3, 2], [4, 5]], 2))
print("5. Max:", find_max([[1, 2], [3, [4, 5]], 6]))
print("6. Count:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep Flatten:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print("8. Average:", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten: [1, 2, 3, 4, 5]
2. Access: 6
3. Sum: 21
4. Remove: [[1], [3], [4, 5]]
5. Max: 6
6. Count: 3
7. Deep Flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average: 3.5


Numpy

In [27]:
# initialize a 2 x 3 array filled with zeros
zero_matrix = np.zeros((2, 3))

print("Zeros array:\n", zero_matrix)
print("Dimensions:", zero_matrix.shape, "\n")

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Dimensions: (2, 3) 



In [28]:

# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
  print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [29]:
# For a 1-D array:

arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


In [30]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


In [31]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [32]:
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64

int64
float64


In [33]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


In [34]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [35]:
for item in arr_2d.flat:
  print(item, end=" ") # Output: 1 2 3 4 5 6

1 2 3 4 5 6 

In [36]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


In [37]:
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [38]:
lst = [[1, 2], [3, 4]]
#print(lst.shape)
# Error: List has no .shape attribute
#Fixing the Error:
arr = np.array(lst)
print(arr.shape) # Output: (2, 2)

(2, 2)


In [39]:
arr = np.array([1, 2, 3])

# Check if array has more than one dimension
if arr.ndim > 1:
    print(arr.shape[1])
else:
    print("Array is 1D, no second dimension")

Array is 1D, no second dimension


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr.shape()) # Error: .shape is an attribute, not a function
print(arr.shape) # Correct usage

(2, 3)


In [41]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2, 3])

try:
    result = a + b
    print(result)
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (2,2) (3,) 


In [42]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [44]:
array = np.array([[1, 2, 3], [4, 5, 6]])
#reshaped_array = array.reshape(4, 2)
# Error: cannot reshape array of size 6 into shape (4, 2)

In [45]:

a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [46]:

# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [47]:
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [49]:
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.33864239e-315 0.00000000e+000 5.78895531e-317]
 [5.78921618e-317 5.78741383e-317 5.78950076e-317]]


In [50]:
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [51]:
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (thirddimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


In [52]:

# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2)) # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [53]:

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]]) # shape (2, 2)
# Attempting horizontal stack (this will fail)
try:
  hstacked = np.hstack((arr1, arr2)) # Error due to shape mismatch
except ValueError as e:
  print(f"Error: {e}")
# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) # shape (2, 3)
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [54]:
arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=int)

# Convert arr2 to column shape
arr2 = arr2.reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

[[1 2 5]
 [3 4 6]]


In [55]:
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]])   # shape (2, 2)
arr2 = np.array([5, 6])             # shape (2,)

# Attempting horizontal stack
try:
    hstacked = np.hstack((arr1, arr2))   # Error due to dimension mismatch
except ValueError as e:
    print(f"Error: {e}")

# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1)   # shape (2,1)

hstacked = np.hstack((arr1, arr2))      # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [56]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]])        # shape (2, 2)

# Attempting horizontal stack (this will fail)
try:
    hstacked = np.hstack((arr1, arr2))   # Error due to shape mismatch
except ValueError as e:
    print(f"Error: {e}")

# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]])   # shape (2, 3)

hstacked = np.hstack((arr1, arr2))   # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [57]:
arr1 = np.array([[1, 2], [3, 4]], dtype=int)
arr2 = np.array([5, 6], dtype=float)

# Reshape arr2 to make dimensions compatible
arr2 = arr2.reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

# Convert datatype to match arr1
arr2 = np.array([5, 6], dtype=int).reshape(2,1)

hstacked = np.hstack((arr1, arr2))
print(hstacked)

[[1. 2. 5.]
 [3. 4. 6.]]
[[1 2 5]
 [3 4 6]]


In [58]:
arr1 = np.array([[[1, 2], [3, 4]]])   # shape (1, 2, 2)
arr2 = np.array([[5, 6], [7, 8]])     # shape (2, 2)

# Attempting stacking with 3D and 2D arrays
try:
    vstacked = np.vstack((arr1, arr2))   # Error due to different dimensions
except ValueError as e:
    print(f"Error: {e}")

# Solution: Reshape arr1 to be 2D
arr1 = arr1.reshape(2, 2)   # Now shape becomes (2,2)

vstacked = np.vstack((arr1, arr2))   # Works fine
print(vstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


In [60]:

# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
  print(array[2, 1])
except IndexError as e:
  print(f"Error: {e}")

Error: index 2 is out of bounds for axis 0 with size 2


In [61]:

# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [62]:

# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

In [63]:

# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [64]:

A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [65]:
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [66]:
A = np.ones((3,2)) # Shape (3,2)
B = np.ones((2,3)) # Shape (2,3)
C = A + B #ValueError: operands could not be broadcast together

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [68]:
A = np.ones((3,2))
B = np.ones((3,2))

C = A + B
print(C)

[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [69]:
import numpy as np
import time

# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Using a loop
start_time = time.time()
result_loop = np.zeros(size)

for i in range(size):
    result_loop[i] = a[i] + b[i]

end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")

# Using NumPy vectorized operations
start_time = time.time()

result_vectorized = a + b   # Element-wise addition

end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")

# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.98102 seconds
Vectorized Execution Time: 0.01246 seconds
Vectorization is approximately 78.72 times faster!


Numpy Exercise

In [70]:
#Problem:1
import numpy as np

# Initialize an empty array (2x2)
empty_arr = np.empty((2, 2))
print(" Empty Array (2x2):")
print(empty_arr)

# Initialize an all ones array (4x2)
ones_arr = np.ones((4, 2))
print("\n Ones Array (4x2):")
print(ones_arr)

# New array of given shape filled with a specific value
full_arr = np.full((3, 3), 7)
print("\n Full Array (3x3 filled with 7):")
print(full_arr)
print(f"Shape: {full_arr.shape}, Data Type: {full_arr.dtype}")

# New array of zeros with same shape and type as the full array
zeros_like_arr = np.zeros_like(full_arr)
print("\n Zeros Like Array:")
print(zeros_like_arr)

#  New array of ones with same shape and type as the full array
ones_like_arr = np.ones_like(full_arr)
print("\n Ones Like Array:")
print(ones_like_arr)

# Convert list to NumPy array
new_list = [1, 2, 3, 4]
np_arr = np.array(new_list)
print("\n Array from List:")
print(np_arr)

 Empty Array (2x2):
[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]

 Ones Array (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Full Array (3x3 filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Shape: (3, 3), Data Type: int64

 Zeros Like Array:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

 Ones Like Array:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

 Array from List:
[1 2 3 4]


In [71]:
#Problem:2
import numpy as np

#  Create an array with values from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:")
print(arr1)

# Create a 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n 3x3 Matrix from 0 to 8:")
print(arr2)

# Create a 3x3 identity matrix
identity = np.eye(3)
print("\n 3x3 Identity Matrix:")
print(identity)

# Create a random array of size 30 and find the mean
rand_arr = np.random.random(30)
print("\n Random Array of size 30:")
print(rand_arr)
print("Mean of the array:", rand_arr.mean())

# Create a 10x10 array with random values and find min & max
rand_matrix = np.random.random((10, 10))
print("\n 10x10 Random Array:")
print(rand_matrix)
print("Minimum:", rand_matrix.min(), "Maximum:", rand_matrix.max())

#  Create a zero array of size 10 and replace 5th element with 1
zeros_arr = np.zeros(10)
zeros_arr[4] = 1
print("\n Zero Array with 5th element = 1:")
print(zeros_arr)

# Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n Reversed Array:")
print(reversed_arr)

# Create a 2D array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n 2D Array with 1 on border and 0 inside:")
print(border_arr)

#  Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n 8x8 Checkerboard Pattern:")
print(checkerboard)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

 3x3 Matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 Random Array of size 30:
[0.17977642 0.59834172 0.0425366  0.70865231 0.82312177 0.86073922
 0.11408666 0.92722973 0.86991786 0.75359102 0.79398996 0.03408872
 0.96439938 0.32816901 0.97111632 0.51471627 0.81383909 0.17729393
 0.86484807 0.42408796 0.83539648 0.55523729 0.92759525 0.05968163
 0.28431173 0.07387326 0.77555954 0.95763105 0.82609918 0.58900253]
Mean of the array: 0.5882976651247366

 10x10 Random Array:
[[0.73332156 0.82558016 0.40738024 0.57259048 0.92750674 0.5951668
  0.38938798 0.72306896 0.03069873 0.56351419]
 [0.44665082 0.49715514 0.0306356  0.51642571 0.57107639 0.32455843
  0.29025508 0.94753968 0.57205278 0.12308858]
 [0.69404308 0.84060807 0.40131752 0.22141341 0.58481856 0.03974154
  0.76233624 0.9427794

In [72]:
#Problem 3:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the two arrays
print("Addition of x and y:\n", x + y)

#  Subtract the two arrays
print("\nSubtraction of x and y:\n", x - y)

# Multiply array with integer
print("\n x multiplied by 3:\n", x * 3)

# Square of each element
print("\n Square of x elements:\n", x ** 2)

#  Dot products
print("\n Dot Product of v and w:", np.dot(v, w))
print("Dot Product of x and v:", np.dot(x, v))
print("Dot Product of x and y:\n", np.dot(x, y))

# Concatenate
print("\n Concatenate x and y along rows (vstack):\n", np.vstack((x, y)))
print("Concatenate v and w as column (reshape + vstack):\n", np.vstack((v, w)).T)

#  Attempt to concatenate x and v (expecting error)
try:
    np.vstack((x, v))
except ValueError as e:
    print("\n Attempt to concatenate x and v error:\n", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

 x multiplied by 3:
 [[ 3  6]
 [ 9 15]]

 Square of x elements:
 [[ 1  4]
 [ 9 25]]

 Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]

 Concatenate x and y along rows (vstack):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w as column (reshape + vstack):
 [[ 9 11]
 [10 12]]


In [73]:
#Problem4:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#  Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1 = Identity Matrix:\n", np.dot(A, A_inv))

# Prove AB != BA
print("\n AB:\n", np.dot(A, B))
print("BA:\n", np.dot(B, A))
print("Check AB != BA:", not np.allclose(np.dot(A,B), np.dot(B,A)))

# Prove (AB)^T = B^T A^T
left = np.dot(A, B).T
right = np.dot(B.T, A.T)
print("\n (AB)^T:\n", left)
print("B^T A^T:\n", right)
print("Check equality:", np.allclose(left, right))

#  Solve system of equations using inverse method
# Equations: 2x - 3y + z = -1, x - y + 2z = -3, 3x + y - z = 9
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constants = np.array([-1, -3, 9])

solution = np.dot(np.linalg.inv(coeff_matrix), constants)
print("\n Solution of the system (x, y, z):\n", solution)

A * A^-1 = Identity Matrix:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Check AB != BA: True

 (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Check equality: True

 Solution of the system (x, y, z):
 [ 2.  1. -2.]


In [74]:
import time
import numpy as np

# 1. Setup
size = 1_000_000  # 1 million elements
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.arange(size)
arr2 = np.arange(size)


# 2. Element-wise Addition

# Python lists
start = time.time()
res_list_add = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(f"Python List Addition: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
res_np_add = arr1 + arr2
end = time.time()
print(f"NumPy Array Addition: {end - start:.5f} seconds")

# 3. Element-wise Multiplication

# Python lists
start = time.time()
res_list_mul = [x * y for x, y in zip(list1, list2)]
end = time.time()
print(f"Python List Multiplication: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
res_np_mul = arr1 * arr2
end = time.time()
print(f"NumPy Array Multiplication: {end - start:.5f} seconds")

# 4. Dot Product

# Python lists
start = time.time()
dot_list = sum(x * y for x, y in zip(list1, list2))
end = time.time()
print(f"Python List Dot Product: {end - start:.5f} seconds")

# NumPy arrays
start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy Array Dot Product: {end - start:.5f} seconds")


# 5. Matrix Multiplication

matrix_size = 300  # smaller to avoid MemoryError in Python lists
# Python lists
list_matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
list_matrix2 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]

start = time.time()
result_list_matrix = [
    [sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)]
    for row in list_matrix1
]
end = time.time()
print(f"Python List Matrix Multiplication: {end - start:.5f} seconds")

# NumPy arrays
np_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
np_result = np.matmul(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy Matrix Multiplication: {end - start:.5f} seconds")

Python List Addition: 0.07908 seconds
NumPy Array Addition: 0.00512 seconds
Python List Multiplication: 0.08233 seconds
NumPy Array Multiplication: 0.00565 seconds
Python List Dot Product: 0.08762 seconds
NumPy Array Dot Product: 0.00180 seconds
Python List Matrix Multiplication: 3.35810 seconds
NumPy Matrix Multiplication: 0.02894 seconds
